close all; clear; %clear classes; %clc;

%Create ground link
Ground = SRD_get_Link_Ground();

index = 1;
Link_1 = SRD_get_Link(...
    'Order', index, ...
    'Name', 'Link_1', ...
    'RelativeBase', zeros(3, 1), ...
    'RelativeFollower', [0;0;0.5], ...
    'RelativeCoM', [0;0;0.25], ...
    'Mass', 10, ...
    'Inertia', diag([1/12*10*0.5, 1/12*10*0.5, 0.1*1/12*10*0.5]), ...
    'ToDisplay', true, ...
    'Color', 'r', ...
    'StlPath', []);

Joint_1 = SRD_get_Joint_PivotX(...
    'Name', 'Joint_1', ...
    'ChildLink',  Link_1, ...
    'ParentLink', Ground, ...
    'ParentFollowerNumber', 1, ...
    'UsedGeneralizedCoordinates', 1, ...
    'UsedControlInputs', 1, ...
    'DefaultJointOrientation', eye(3));


index = index + 1;
Link_2 = SRD_get_Link(...
    'Order', index, ...
    'Name', 'Link_2', ...
    'RelativeBase', zeros(3, 1), ...
    'RelativeFollower', [0;0;0.5], ...
    'RelativeCoM', [0;0;0.25], ...
    'Mass', 10, ...
    'Inertia', diag([1/12*10*0.5, 1/12*10*0.5, 0.1*1/12*10*0.5]), ...
    'ToDisplay', true, ...
    'Color', 'r', ...
    'StlPath', []);

Joint_2 = SRD_get_Joint_PivotX(...
    'Name', 'Joint_1', ...
    'ChildLink',  Link_2, ...
    'ParentLink', Link_1, ...
    'ParentFollowerNumber', 1, ...
    'UsedGeneralizedCoordinates', 2, ...
    'UsedControlInputs', 2, ...
    'DefaultJointOrientation', eye(3));


index = index + 1;
Link_3 = SRD_get_Link(...
    'Order', index, ...
    'Name', 'Link_3', ...
    'RelativeBase', zeros(3, 1), ...
    'RelativeFollower', [0;0;0.5], ...
    'RelativeCoM', [0;0;0.25], ...
    'Mass', 10, ...
    'Inertia', diag([1/12*10*0.5, 1/12*10*0.5, 0.1*1/12*10*0.5]), ...
    'ToDisplay', true, ...
    'Color', 'r', ...
    'StlPath', []);

Joint_3 = SRD_get_Joint_PivotX(...
    'Name', 'Joint_1', ...
    'ChildLink',  Link_3, ...
    'ParentLink', Link_2, ...
    'ParentFollowerNumber', 1, ...
    'UsedGeneralizedCoordinates', 3, ...
    'UsedControlInputs', 3, ...
    'DefaultJointOrientation', eye(3));


LinkArray = [Ground; Link_1; Link_2; Link_3]; %Create array of links
SRD_save(LinkArray, 'LinkArray');

InitialPosition = [pi/4; -2*pi/3; 3.5*pi/5]; %Define initial position of the robot
SRD_save(InitialPosition, 'InitialPosition');

Chain = SRD_Chain(LinkArray);
SRD_save(Chain, 'Chain');
%Chain.Update(InitialPosition)


SRD_SetupVisuals('AxisLimits', [-1; 1; -1; 1; -1; 1], ...
    'ViewAngle', [-37.5, 30], ...
    'ToDrawMeshes', false, ...
    'Animation_ToUseGrid', true, ...
    'Animation_ToUseGridMinor', true, ...
    'DrawRobot_Default_RobotColor', [0.6 0.3 0], ...
    'DrawRobot_Default_EdgeAlpha', 0.3, ...
    'DrawRobot_Default_FaceAlpha', 1, ...
    'DrawRobot_Default_LineWidth', 0.5, ...
    'DrawRobot_STL_FaceColor', [0.8 0.8 1.0], ...
    'DrawRobot_STL_EdgeColor', 'none', ...
    'DrawRobot_STL_FaceLighting', 'gouraud', ...
    'DrawRobot_STL_AmbientStrength', 0.15, ...
    'DrawRobot_STL_camlight', 'headlight', ...
    'DrawRobot_STL_material', 'metal', ... %shiny dull metal
    'ToDrawFrames', false, ...
    'DrawRobot_Frame_Scale', 0.2, ...
    'DrawRobot_Frame_LineWidth', 1);

DrawRobot_function = SRD_DrawRobot_get_function('DrawRobot_Type', 'Default', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', [], ...
    'Function_Type', 'DrawGivenPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'Chain', Chain);

DrawRobot_function(InitialPosition, [])
SRD__make_default_scene('Default')
            
